[project]
name = "typing-speed-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotext>=5.3.2",
    "tabulate>=0.9.0",
]
